### ISSUE TITLE
How to run the app without installing foreman.

### ISSUE THREAD

**Issue by korenhskoh** [bborn/howdoi.ai#10]
Hi ,

Sorry for asking this topic question again. I'm new to here. 

I just want to run this app and also saw the note mentioned not need to install foreman. 

I try run the python app.py in the terminal but got keyerror or is something i get it. 
How to run the app after all requirement.txt have been installed . 

 

Thank you ?

**Comment by radman-x** [comment]
From a Windows command terminal or a Linux bash prompt type these two lines:

flask --debug run --port 9000
cd vite && yarn autobuild

Then point your browser at http://127.0.0.1:9000/.

Once you’ve run the second line above once, you don’t need to run it again, unless you change some code under vite directory.
