### ISSUE TITLE
Get Keyerror from os.environ[NEWS_API_KEY]

### ISSUE THREAD

**Issue by korenhskoh** [bborn/howdoi.ai#11]
Hi , 

I got the error of this keyerror raised towards environment var and double checked my api key was insert correctly in .env file.
    news_api_key = os.environ['NEWS_API_KEY']
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'NEWS_API_KEY'

any advice for this ?

**Comment by bborn** [comment]
I'm assuming your .env isn't being loaded correctly.
