### ISSUE TITLE
Incorrect Initial URL Retrieval

### ISSUE THREAD

**Issue by Encrypted42** [bborn/howdoi.ai#4]
When prompted for a particular list of links to be included in HowDoI's current response regarding various companies, the first link was wrong (and also did not exist, although a different domain suffix of the incorrect URL existed somewhere on the internet). 

When told that it was incorrect and asked to fix the first link, it provided the correct link. 

When asked why it had done the error, the response was that it had "misread" the website, as it had looked for a site that "started with the letter [a] and ended with [letter b].com".

**Comment by bborn** [comment]
Hmm... that seems like a pretty complex query - not sure the LLM model can handle it. Can you share what the exact where was?

**Comment by Encrypted42** [comment]
Sure, Here is the entire conversation for this particular instance. (might be a bit blurred haha)

![incorrectURL](https://user-images.githubusercontent.com/124825126/217646708-87dbcd10-b85f-4a20-a801-eae357cb10cb.png)


Also: potentially relevant? (see below)
Not sure if it would be helpful to make a myriad of issue posts rn.. I assume all this is still very much so a work in progress. 
Cool stuff tho!

![image](https://user-images.githubusercontent.com/124825126/217646932-81287cd6-b866-4808-9539-4a6abf45af80.png)

![image](https://user-images.githubusercontent.com/124825126/217645863-fc57c925-9478-4bf9-9225-3dbbffc0ab03.png)
