### ISSUE TITLE
No such file or directory: 'autobuild'

### ISSUE THREAD

**Issue by tatakof** [bborn/howdoi.ai#6]
Hello, great repo!

I'm running the codebase as it is (with the some of the keys added but not all), but when I run `foreman start  -f Procfile.local`

I get the following error: 

```
02:57:39 vite.1 | started with pid 57889
00h00m00s 0/0: : 02:57:39 vite.1 | ERROR: [Errno 2] No such file or directory: 'autobuild'
02:57:40 vite.1 | exited with code 1
02:57:40 system | sending SIGTERM to all processes
```

Everyfile is untouched by me (except for the keys), should I modify the Procfile or Procfile.local to avoid the "no such file or directory: 'autobuild' error? or how can I fix it? 
Thanks

**Comment by bborn** [comment]
Are you able to run `yarn autobuild` within the `vite` directory?

**Comment by neosanma** [comment]
Nope, running `yarn autobuild` within the vite directory yields (sortof) the same error: 
````❯ yarn autobuild    (nlp) 
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'autobuild'```
Am I supoused to have an autobuild file inside vite?

**Comment by bborn** [comment]
`yarn autobuild` just runs `vite build --watch` via the `package.json` scripts config. Can you run `vite build --watch`?
 What about `yarn run autobuild`?

What version of yarn do you have?

**Comment by neosanma** [comment]
running `vite build --watch` both outside and within /vite yields: 

```
❯ vite build --watch      (nlp) 
vite: invalid option -- '-'
vite: invalid option -- 'w'
vite: invalid option -- 'a'
Interval is not in the correct format [%d:%d]

Usage: vite [OPTION...] [[-f] inputfile] [-e outputfile] 

  -h                 display this help                  
  -f inputfile       open the inputfile                 
  -a                 display all the inputfile (Default)
  -t [T0]:[T1]       display the interval [T0:T1] (Default: T0 = 0 and T1 = Tmax)
  -e outputfile      export the trace file in the svg format to outpufile
  -c xmlfile         import a list of containers to display from an xml file
```

whereas running `yarn run autobuild` yields
```
❯ yarn run autobuild      (nlp) 
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
```

yarn version: 
```
❯ yarn --version          (nlp) 
0.32+git

```

**Comment by bborn** [comment]
Can you upgrade your `yarn`? I have version 1.22.19, so I think your version is quite old.

**Comment by neosanma** [comment]
Updating fixed the issue. Thanks
