### ISSUE TITLE
Can I run this without installing Foreman (esp. Ruby) on Windows?

### ISSUE THREAD

**Issue by radman-x** [bborn/howdoi.ai#7]
I am trying to run your nice repo on Windows 10 without installing Foreman (and, esp. without installing Ruby on Windows which is a real pain).

Can I do this simply by running the ProcFile.local commands in a terminal, either normal Windows prompt or WSL? Like this:

   flask --debug run --port 9000
   cd vite && yarn autobuild

**Comment by bborn** [comment]
Yes - you can just run those commands individually.

**Comment by radman-x** [comment]
OK, thanx for the fast response. This seems to be working, once I got all the requirements installed, but I'm having other issues. I'll close this and open some other cases.
