### ISSUE TITLE
Getting error "supabase.client.SupabaseException: supabase_url is required" when running flask directly.

### ISSUE THREAD

**Issue by radman-x** [bborn/howdoi.ai#8]
Added in (some) of the API keys.

Then, have several issues when directly running "flask --debug run --port 9000".

First, got the following warning 
* Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
So, I installed python-dotenv and no longer get that error. You may want to update your requirements.txt file.

Second, now getting following error "supabase.client.SupabaseException: supabase_url is required". Full stack trace:

flask --debug run --port 9000
Traceback (most recent call last):

supabase.client.SupabaseException: supabase_url is required

**Comment by bborn** [comment]
Can you try again - I ripped out that supabase stuff.

**Comment by radman-x** [comment]
Got this all up and running now! Thnx for your help.

A few additional tips that may be helpful for others trying to get this up and running (you may want to add some of these to the docs and/or README):

- You may need to install the Vite project dependencies by cd into ./vite and running "npm install" (not sure if Vite autobuild does this, haven't used Vite before, but I don't think it does).

- As mentioned in #7, you do NOT need to install Foreman nor Hivemind -- can just execute the commands in #7 in a terminal prompt. Note: you may need to open two terminal prompts, one for the Flask server and one for the front end Javascript.

Again, thnx for your help and writing such a great repo.
